### ISSUE TITLE
Can't build project with this framework version,

### ISSUE THREAD

**Issue by datnm** [nttcom/SkyWay-iOS-SDK#3]
I use version 0.2.1 then ok,
When update framework to this version (0.2.2),
I can't build project with framework,
please check again.

**Comment by rokihiro** [comment]
We are sorry for any inconvenience.
Did you downlod from DOWNLOAD ZIP button ?
If so, could you downlod from [here](https://s3-ap-northeast-1.amazonaws.com/skyway-sdk-production/skyway-ios-sdk.zip)? 
It's same as this repository.

We are using Git Large File Storage from v0.2.2.
Because SkyWay.framework is too big to put github repository.(over 100MB)
If you download them from DOWNLOAD ZIP button, SkyWay.framework doesn't contain binary file.

You can download below.
1. download from [here](https://s3-ap-northeast-1.amazonaws.com/skyway-sdk-production/skyway-ios-sdk.zip)? 
2. download from this repository using 'git clone https://github.com/nttcom/SkyWay-iOS-SDK.git'

Sincerely

**Comment by tsu-takahashi** [comment]
FYI: A build error messages in this case will be like as follows.
If you encountered an error like this, please check the above comment.
We are sorry for any inconvenience.

```
ld: warning: ignoring file /[project-directory]/SkyWay.framework/SkyWay, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (x86_64): /[project-directory]/SkyWay.framework/SkyWay
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_SKWConnectOption", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_SKWDataConnection", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_SKWPeer", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_SKWPeerError", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_SKWPeerOption", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
